### ISSUE TITLE
[IDEA] Rename Tanomaly's parameter "learning_mode"

### ISSUE THREAD

**Issue by frikilax** [VultureProject/darwin#102]
**What is your feature about ?**
The FTanomaly filter's body parameter "learning_mode" doesn't represent a learning mode for the IA model, but just toggles the thread detecting every X minutes entries in Redis.

**If your request is about an existing filter/functionality**
 - TAnomaly

**Describe what you'd like**
This field should be named something like "activate_detection" or something.

**Comment by HugoSoszynski** [comment]
Obsolete. Field removed in previous release (v1.2.7).
