### ISSUE TITLE
[IDEA] Refactor & Merge Anomaly and TAnomaly

### ISSUE THREAD

**Issue by HugoSoszynski** [VultureProject/darwin#103]
**What is your feature about ?**

Merging Anomaly & TAnomaly algorithm in one class (if possible).

Merging both filter into one and add the possibility to choose either Anomaly or TAnomaly behavior in configuration file.

**Comment by GregoireGonzalez** [comment]
This issue is obsolete due to the arrival of filter Buffer. Closing it.
