### ISSUE TITLE
[BUG] Multiple instance of identical tanomaly on the same redis replicaset

### ISSUE THREAD

**Issue by HugoSoszynski** [VultureProject/darwin#168]
**Describe the bug**
Given that you have:
- multiple machines
- a REDIS instance of the same replicaset on each machine
- a replicated tanomaly instance on each machine
The tanomaly instances fetch data from the same list in REDIS at different time intervals thus corrupting results.

**Expected behavior**
All tanomaly MUST be able to push data into the REDIS list.
Only the tanomaly on the same machine as the MASTER REDIS replica fetch the data for processing.

**Additional context**
This can be easily tested in a Vulture4 cluster and will be used inside of it.

**Comment by frikilax** [comment]
resolved in #172
