### ISSUE TITLE
[BUG] filter launched with correct parameters, but will return an error instead

### ISSUE THREAD

**Issue by frikilax** [VultureProject/darwin#180]
**Describe the bug**
when launching filter with good parameters and configuration, filter won't launch and prints an error in logs:
![image](https://user-images.githubusercontent.com/33118448/82459008-b2579b80-9ab7-11ea-8ef4-d328ba48a65d.png)
Seems to happen generally when a numerical value is zero.

**Plateform (please complete the following information):**
 - OS (version): CentOS 8
 - Darwin version: 1.2.6

**To Reproduce**
Won't always happen:
1. make sure you have a valid configuration/environment
2. configure a filter with cache size at zero (0)
3. launch the filter (either manually or via manager)

**Comment by HugoSoszynski** [comment]
Closed by #181
