### ISSUE TITLE
[BUG] Manager hangs if an update command is sent with a wrong configuration file

### ISSUE THREAD

**Issue by frikilax** [VultureProject/darwin#211]
**Describe the bug**
if an error is put in the manager configuration file, and the manager is reloaded with an admin command, the parsing of the configuration file fails and the manager hangs after sending a critical error

**Plateform (please complete the following information):**
 - OS (version): HBSD12.2
 - Darwin version: 1.4

**To Reproduce**
1. Setup a correct configuration file (with a single running filter for example)
2. Run Darwin, the manager and the filter should work correctly
3. Modify the configuration file, so that it is not a valid json (add characters at the beginning of the file, for example)
4. send a `{"type": "update_filters"}` command to the manager
5. netcat should hang indefinitely, and darwin_manager.log should show a CRITICAL log

**Expected behavior**
Manager __should invalidate__ the configuration file, but shouldn't fail and hang after reading it, its state should remain the same.

**Screenshots/logs**
![image](https://user-images.githubusercontent.com/33118448/98651369-7270c300-233a-11eb-9ef2-7ce3718f74a6.png)
![image](https://user-images.githubusercontent.com/33118448/98651393-7ac8fe00-233a-11eb-886d-634882904fa6.png)

**Comment by HugoSoszynski** [comment]
Closed by #217
