### ISSUE TITLE
[BUG] redis not flushed between tests

### ISSUE THREAD

**Issue by frikilax** [VultureProject/darwin#79]
**Describe the bug**
"connection: new_connection_test" test of connection filter failing after successive calls to testing

**Plateform (please complete the following information):**
 - OS (version): [e.g. FreeBSD (12.0)]
 - Darwin version: [e.g. 1.0]

**To Reproduce**
1. Make sure redis is running and listening on /var/sockets/redis/redis.sock
2. Start the tests.py once
3. Wait for connection tests to finish
4. Stop the tests
5. launch them a second time immediately
6. Wait for first connection filter test
7. Now test fails

**Expected behavior**
The test should be OK both times

**Solution**
The Redis cache is not cleared after/before the tests, so the previous entry (added by the filter on the first run) stays and pollutes the second run

**Comment by HugoSoszynski** [comment]
Running a FLUSHALL after the tests might be a good idea.

**Comment by NS4nti** [comment]
> Running a FLUSHALL after the tests might be a good idea.

Yes, and maybe warn somewhere that the Redis will be flushed

**Comment by HugoSoszynski** [comment]
Moving to 1.1 because associated PR #99 depends on coming changes for #98

**Comment by frikilax** [comment]
flogs OK since #100 
fconnection OK with #99 

the only 2 filters with tests using redis, so Issue is closed
