### ISSUE TITLE
[BUG] Filter DGA crash when Generator is unable to configure the filter

### ISSUE THREAD

**Issue by NS4nti** [VultureProject/darwin#91]
**Describe the bug**
When the DGA's generator return False, the filter crash and didn't remove the PID file. **Seen in the [fix-dga](https://github.com/VultureProject/darwin/tree/fix-fdga) branch because the Generator Configure is fixed to return False instead of crashing when bad token map is given**

After investigation : At line 34 in Core.cpp, the generator Configure return false and the end of the function is reached. But line 42 in main.cpp, when we normally remove the PID file, is not reached. Maybe the `raise(SIGTERM)` at line 36 in the Core.cpp is in cause ?

See if the bug is same with others filters

**Plateform (please complete the following information):**
 - OS (version): FreeBSD 12.0
 - Darwin version: 1.1

**To Reproduce**
1. Checkout in the [fix-dga](https://github.com/VultureProject/darwin/tree/fix-fdga) branch
2. Call the dga filter with a Token Map with wrong format (a file with just a blank line is fine)

**Expected behavior**
The PID file is not removed.

In the log you should have : 
```
{"date":"Fri Oct 18 14:05:31 2019","level":"CRITICAL","filter":"dga_2","message":"DGA:: LoadTokenMap:: Error when load token map : Blank lie"}
{"date":"Fri Oct 18 14:05:31 2019","level":"CRITICAL","filter":"dga_2","message":"Core:: Run:: Unable to configure the filter"}
{"date":"Fri Oct 18 14:05:31 2019","level":"DEBUG","filter":"dga_2","message":"Server::Handle:: Closing acceptor"}
{"date":"Fri Oct 18 14:05:31 2019","level":"INFO","filter":"dga_2","message":"Monitor::HandleAccept:: Acceptor closed, closing monitor..."}
```
But no log about removing the PID.

**Comment by frikilax** [comment]
Bug seems to not happen anymore, so this won't be worked on for now.
If it were to happen again, a potential fix would be to ignore SIGTERM in main before raising it, to completely ignore the signal for ourselves and only send it to threads.
