### ISSUE TITLE
[IDEA] Use Redis PUB/SUB instead of regular keys for log alerts

### ISSUE THREAD

**Issue by frikilax** [VultureProject/darwin#93]
**What is your feature about ?**
change the way the Logs filter notifies alerts in Redis.

**If your request is about an existing filter/functionality**
Flogs

**Describe what you'd like**
Logs is currently logging alerts to redis using a regular key, this key is then fetched by third-parties at regular intervals for their workflows (Vulture, for example).
The enhancement would be to instead publish alerts in a Redis channel, using its [PUB/SUB system](https://redis.io/topics/pubsub) to allow third-parties to be notified immediately of new alerts (instead of regular time-interval pollings).

**Additional context**
Flogs could have an additional parameter, *redis_channel*, that allows it to publish to redis on the given channel.
This could allow Flogs to work for regular Redis keys AND for Redis channels

**Comment by HugoSoszynski** [comment]
As we plan to remove flogs (#104) this could be a new "AlerRepository"
